using Microsoft.CodeAnalysis.CSharp;

namespace CodeScanner;

public sealed class CSharpSmellAnalyzer : ISmellAnalyzer
{
    private const int AutoGeneratedScanLines = 5;

    public SmellAnalysisResult Analyze(string filePath, string content)
    {
        if (string.IsNullOrEmpty(content))
        {
            return new SmellAnalysisResult(Array.Empty<SmellFinding>(), 0);
        }
        if (IsAutoGenerated(content))
        {
            return new SmellAnalysisResult(Array.Empty<SmellFinding>(), 0);
        }

        var tree = CSharpSyntaxTree.ParseText(content, path: filePath);
        var root = tree.GetRoot();
        var findings = new List<SmellFinding>();
        var walker = new SmellWalker(filePath, findings);
        walker.Visit(root);
        return new SmellAnalysisResult(findings, walker.TotalFunctions);
    }

    private static bool IsAutoGenerated(string content)
    {
        const string marker = "<auto-generated";
        var lines = content.Split('\n');
        var max = Math.Min(AutoGeneratedScanLines, lines.Length);
        for (var i = 0; i < max; i++)
        {
            if (lines[i].Contains(marker, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }
        return false;
    }
}
