using System.Text;

namespace CodeScanner.Tests.Analyzers;

public class CSharpSmellAnalyzerTests
{
    private static readonly CSharpSmellAnalyzer Analyzer = new();

    private static string ManyLines(int n)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < n; i++) { sb.Append("        var x").Append(i).Append(" = 1;\n"); }
        return sb.ToString();
    }

    [Fact]
    public void ShortMethod_NoFindings()
    {
        var src = "class C { void Foo() { var x = 1; } }";
        Assert.Empty(Analyzer.Analyze("a.cs", src));
    }

    [Fact]
    public void LongFunction_50Lines_NoFinding()
    {
        var body = ManyLines(48);
        var src = $"class C {{\n    void Foo() {{\n{body}    }}\n}}";
        var findings = Analyzer.Analyze("a.cs", src).Where(f => f.Type == "long_function").ToList();
        Assert.Empty(findings);
    }

    [Fact]
    public void LongFunction_60Lines_LowSeverity()
    {
        var body = ManyLines(60);
        var src = $"class C {{\n    void Foo() {{\n{body}    }}\n}}";
        var findings = Analyzer.Analyze("a.cs", src).Where(f => f.Type == "long_function").ToList();
        Assert.Single(findings);
        Assert.Equal("low", findings[0].Severity);
        Assert.Equal("Foo", findings[0].Name);
    }

    [Fact]
    public void LongFunction_100Lines_MediumSeverity()
    {
        var body = ManyLines(100);
        var src = $"class C {{\n    void Foo() {{\n{body}    }}\n}}";
        var findings = Analyzer.Analyze("a.cs", src).Where(f => f.Type == "long_function").ToList();
        Assert.Single(findings);
        Assert.Equal("medium", findings[0].Severity);
    }

    [Fact]
    public void LongFunction_200Lines_HighSeverity()
    {
        var body = ManyLines(200);
        var src = $"class C {{\n    void Foo() {{\n{body}    }}\n}}";
        var findings = Analyzer.Analyze("a.cs", src).Where(f => f.Type == "long_function").ToList();
        Assert.Single(findings);
        Assert.Equal("high", findings[0].Severity);
    }

    [Fact]
    public void LongParameterList_5Params_NoFinding()
    {
        var src = "class C { void Foo(int a, int b, int c, int d, int e) { } }";
        Assert.DoesNotContain(Analyzer.Analyze("a.cs", src), f => f.Type == "long_parameter_list");
    }

    [Fact]
    public void LongParameterList_6Params_LowSeverity()
    {
        var src = "class C { void Foo(int a, int b, int c, int d, int e, int f) { } }";
        var findings = Analyzer.Analyze("a.cs", src).Where(f => f.Type == "long_parameter_list").ToList();
        Assert.Single(findings);
        Assert.Equal("low", findings[0].Severity);
        Assert.Equal(6, findings[0].Value);
    }

    [Fact]
    public void LongParameterList_12Params_HighSeverity()
    {
        var src = "class C { void Foo(int a,int b,int c,int d,int e,int f,int g,int h,int i,int j,int k,int l) { } }";
        var findings = Analyzer.Analyze("a.cs", src).Where(f => f.Type == "long_parameter_list").ToList();
        Assert.Single(findings);
        Assert.Equal("high", findings[0].Severity);
    }

    [Fact]
    public void DeepNesting_4Levels_NoFinding()
    {
        var src = @"
class C {
    void Foo() {
        if (true) {
            if (true) {
                if (true) {
                    var x = 1;
                }
            }
        }
    }
}";
        Assert.DoesNotContain(Analyzer.Analyze("a.cs", src), f => f.Type == "deep_nesting");
    }

    [Fact]
    public void DeepNesting_5Levels_LowSeverity()
    {
        var src = @"
class C {
    void Foo() {
        if (true) {
            if (true) {
                if (true) {
                    if (true) {
                        var x = 1;
                    }
                }
            }
        }
    }
}";
        var findings = Analyzer.Analyze("a.cs", src).Where(f => f.Type == "deep_nesting").ToList();
        Assert.Single(findings);
        Assert.Equal("low", findings[0].Severity);
        Assert.Equal(5, findings[0].Value);
    }

    [Fact]
    public void Lambdas_DoNotTriggerLongFunction()
    {
        var sb = new StringBuilder();
        sb.AppendLine("class C { void Foo() {");
        sb.AppendLine("    System.Action a = () => {");
        for (var i = 0; i < 80; i++) { sb.AppendLine("        var x = 1;"); }
        sb.AppendLine("    }; } }");

        var findings = Analyzer.Analyze("a.cs", sb.ToString())
            .Where(f => f.Type == "long_function").ToList();

        Assert.All(findings, f => Assert.NotEqual(string.Empty, f.Name));
    }

    [Fact]
    public void AutoGeneratedFile_IsSkipped()
    {
        var src = "// <auto-generated>\nclass C { void Foo() { " + ManyLines(80) + " } }";
        var findings = Analyzer.Analyze("Generated.cs", src);
        Assert.Empty(findings);
    }

    [Fact]
    public void Constructor_IsAnalyzed()
    {
        var src = "class C { public C(int a, int b, int c, int d, int e, int f) { } }";
        var findings = Analyzer.Analyze("a.cs", src).Where(f => f.Type == "long_parameter_list").ToList();
        Assert.Single(findings);
        Assert.Equal("C", findings[0].Name);
    }
}
